import type { ButtonHTMLAttributes, ComponentType, HTMLAttributes, InputHTMLAttributes, ReactNode, SelectHTMLAttributes, TextareaHTMLAttributes } from 'react'
import { LoaderCircle } from 'lucide-react'

const join = (...values: Array<string | false | null | undefined>) => values.filter(Boolean).join(' ')
export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger' | 'success'
export type ButtonSize = 'sm' | 'md' | 'lg' | 'icon'

export function buttonClass({ variant = 'secondary', size = 'md' }: { variant?: ButtonVariant; size?: ButtonSize } = {}) {
  const variants = { primary: 'border-app-primary bg-app-primary text-app-primary-fg hover:bg-app-primary-strong', secondary: 'border-app-border bg-app-elevated text-app-text hover:border-app-primary hover:bg-app-surface', ghost: 'border-transparent bg-transparent text-app-muted hover:bg-app-elevated hover:text-app-text', danger: 'border-app-danger bg-app-danger text-white hover:brightness-110', success: 'border-app-success bg-app-success text-app-primary-fg hover:brightness-110' }
  const sizes = { sm: 'min-h-11 px-3 text-sm', md: 'min-h-12 px-4 text-sm', lg: 'min-h-13 px-5 text-base', icon: 'size-11 p-0' }
  return join('inline-flex items-center justify-center gap-2 rounded-xl border font-semibold transition active:scale-[.98] disabled:pointer-events-none disabled:opacity-55', variants[variant], sizes[size])
}

export function Button({ variant = 'secondary', size = 'md', loading, className, children, disabled, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: ButtonVariant; size?: ButtonSize; loading?: boolean }) {
  return <button className={join(buttonClass({ variant, size }), className)} disabled={disabled || loading} aria-busy={loading || undefined} {...props}>{loading && <LoaderCircle className="size-4 animate-spin" aria-hidden="true" />}{children}</button>
}
export function Card({ className, children, padding = 'md', ...props }: HTMLAttributes<HTMLElement> & { padding?: 'md' | 'lg' }) { return <article className={join('rounded-app border border-app-border bg-app-surface shadow-[var(--shadow-card)]', padding === 'lg' ? 'p-6 sm:p-8' : 'p-4 sm:p-5', className)} {...props}>{children}</article> }
export function Badge({ variant = 'neutral', children }: { variant?: 'neutral' | 'primary' | 'success' | 'warning' | 'danger'; children: ReactNode }) { const tones = { neutral: 'border-app-border bg-app-elevated text-app-muted', primary: 'border-app-primary/50 bg-app-primary/10 text-app-primary', success: 'border-app-success/50 bg-app-success/10 text-app-success', warning: 'border-app-warning/50 bg-app-warning/10 text-app-warning', danger: 'border-app-danger/50 bg-app-danger/10 text-app-danger' }; return <span className={join('inline-flex min-h-7 items-center gap-1 rounded-full border px-2.5 text-xs font-bold uppercase tracking-wide', tones[variant])}>{children}</span> }

const control = 'min-h-12 w-full rounded-xl border border-app-border bg-app-elevated px-3.5 text-base text-app-text placeholder:text-app-muted/75 hover:border-app-primary/60 disabled:cursor-not-allowed disabled:opacity-60'
export function Input(props: InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className={join(control, props.className)} /> }
export function Select(props: SelectHTMLAttributes<HTMLSelectElement>) { return <select {...props} className={join(control, props.className)} /> }
export function Textarea(props: TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea {...props} className={join(control, 'min-h-28 py-3', props.className)} /> }
export function Field({ label, hint, children }: { label: string; hint?: string; children: ReactNode }) { return <label className="grid gap-2 text-sm font-semibold text-app-text"><span>{label}</span>{children}{hint && <small className="text-xs font-normal text-app-muted">{hint}</small>}</label> }
export function PageHeader({ eyebrow, title, description, actions }: { eyebrow?: string; title: string; description?: string; actions?: ReactNode }) { return <header className="mb-6 grid gap-2 border-b border-app-border pb-5 sm:grid-cols-[1fr_auto] sm:items-end"><div>{eyebrow && <p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-app-primary">{eyebrow}</p>}<h1 className="text-2xl font-bold tracking-tight text-app-text sm:text-3xl">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm leading-relaxed text-app-muted sm:text-base">{description}</p>}</div>{actions && <div className="flex flex-wrap gap-2">{actions}</div>}</header> }
export function EmptyState({ icon: Icon, title, description, action }: { icon?: ComponentType<{ className?: string }>; title: string; description: string; action?: ReactNode }) { return <div className="rounded-app border border-dashed border-app-border bg-app-surface p-6 text-center">{Icon && <Icon className="mx-auto mb-3 size-7 text-app-primary" />}<h2 className="justify-center text-lg font-semibold text-app-text">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-relaxed text-app-muted">{description}</p>{action && <div className="mt-4 flex justify-center">{action}</div>}</div> }
export function ErrorState({ children, message, action }: { children?: ReactNode; message?: string; action?: ReactNode }) { return <div role="alert" className="my-4 rounded-xl border border-app-danger/50 bg-app-danger/10 p-3 text-sm font-medium text-app-text"><div>{children ?? message}</div>{action && <div className="mt-3">{action}</div>}</div> }
export function LoadingState({ label = 'Caricamento…' }: { label?: string }) { return <div role="status" className="flex min-h-28 items-center justify-center gap-2 text-sm font-medium text-app-muted"><LoaderCircle className="size-5 animate-spin text-app-primary" />{label}</div> }
